services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Test12ing
      - POSTGRES_DB=app_db
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test12ing
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network  

networks:
  app-network:

volumes:
  db_data:

 





